= gpdgen - The Gradle Plugin Descriptor Generator
:!toc:
:!prewrap:
:gradle-docs: https://docs.gradle.org/4.10.2
:version: 0.1.0

image:https://img.shields.io/badge/release-v{version}-blue.svg?style=flat["release v{version}"]
image:https://img.shields.io/badge/license-LGPL--3.0-blue.svg?style=flat["license LGPL-3.0", link="https://www.gnu.org/licenses/lgpl-3.0-standalone.html"]

This repository is the home of gpdgen - the Gradle plugin descriptor generator.

== Introduction
Gradle plugins use properties files (the plugin descriptors) to link a plugin's
id to its implementing class as described in
{gradle-docs}/userguide/custom_plugins.html#sec:custom_plugins_standalone_project[Gradle's custom plugin user guide].

While I think using such an id to identify a plugin is a really great idea,
I quite often forget to update the descriptor's content to reflect the latest
changes to my plugin classes (especially during initial development).

I also like the idea to be able to see which id belongs to a plugin implementation when
looking at the class, but using Javadoc/Groovydoc just seemed not to be the right thing to do.
This would also not be updated automatically on changes to the plugin's id.

So the solution was this: +
Annotate the plugin implementation and a piece of software will take care of creating the plugin
descriptor using the annotations's value and the annotation's class name.

Currently this is available for Gradle plugins written in Groovy, however I plan to provide this
for Java, too.

.Demo Plugin Implementation
[source, groovy]
----
package org.luossfi.gradle.demo.plugins

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.luossfi.gpdgen.common.api.GradlePlugin

@GradlePlugin( 'org.luossfi.demo' )
class DemoPlugin implements Plugin<Project>
{
  void apply( final Project project )
  {
    // lots of useful things
  }
}
----

After compiling the code above there will be the following file in the compile outputs:

.META-INF/gradle-plugins/org.luossfi.demo.properties
[source]
[subs = "attributes"]
----
# Generated by org.luossfi.gpdgen.groovy.transform.GradlePluginAstTransformation (version: {version})
# Generated on 2018-11-12T17:01:00+01:00[Europe/Berlin]
implementation-class = org.luossfi.gradle.demo.plugins.DemoPlugin

----

== Available Modules
[cols="1m, 3"]
|===
|Module Name|Description

|gpdgen-common
|This contains the `@GradlePlugin` annotation and some validation logic.

|gpdgen-groovy
|This is basically a Groovy AST transformation which looks for the `@GradlePlugin`
 annotation and creates the plugin descriptor from it.
|===

== Installation
=== Groovy Projects
[source, gradle]
[subs = "attributes"]
----
apply plugin: 'groovy'

dependencies {
  compileOnly 'org.luossfi.gpdgen:gpdgen-groovy:{version}'
}
----

== Usage
* Annotate the plugin implementation with one or more `@org.luossfi.gpdgen.common.api.GradlePlugin` annotations.
* Each annotation must have a member `value` which defines the plugin's desired id.
* The id must meet these criteria (adapted from
  {gradle-docs}/userguide/custom_plugins.html#sec:creating_a_plugin_id[Gradle's custom plugins user guide]):
** contains only *lower-case* alphanumeric characters (i.e. [0-9a-z]), as well as `.` and `-`
** contains at least one `.` character
** does not start or end with a `.` character
** does not contain any consecutive `.` characters (i.e. `..`)
* The annotated class must be a public, non-abstract class implementing `org.gradle.api.Plugin`.
* Inner classes are not supported.

[NOTE]
====
See the tests in `gpdgen-groovy` for examples on how to use this tool.
====



